base_url = "https://phoracek.github.io"
compile_sass = false
build_search_index = false
theme = "d3c3nt"

[markdown]
highlight_code = true
highlight_theme = "1337"

[extra]
d3_nav = [
  { name = "about", path = "/" },
  { name = "posts", path = "/posts/" }
]
